//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentCourse
    {
        public int AssignmentCourse_Id { get; set; }
        public int Assignment_Id { get; set; }
        public int Course_Id { get; set; }
    
        public virtual Assignments Assignments { get; set; }
        public virtual Courses Courses { get; set; }
    }
}
