//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherCourse
    {
        public int TeacherCourse_Id { get; set; }
        public int Teacher_Id { get; set; }
        public int Course_Id { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
